<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="2210-BGR" failures="2" tests="5" name="Test" time="17.983" errors="0" timestamp="2021-02-12T14:54:39 EET">
  <testcase classname="rough.rough1" name="t2" time="17.0"/>
  <testcase classname="rough.rough1" name="t3" time="0.005"/>
  <testcase classname="rough.rough1" name="t4" time="0.005">
    <failure type="java.lang.AssertionError" message="expected [2] but found [1]">
      <![CDATA[java.lang.AssertionError: expected [2] but found [1]
at rough.rough1.t4(rough1.java:49)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1510)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- t4 -->
  <testcase classname="rough.rough1" name="t5" time="0.003"/>
  <testcase classname="rough.rough1" name="t6" time="0.003">
    <failure type="java.lang.AssertionError" message="expected [2] but found [1]">
      <![CDATA[java.lang.AssertionError: expected [2] but found [1]
at rough.rough1.t6(rough1.java:61)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1510)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- t6 -->
</testsuite> <!-- Test -->
